spring:
  application:
    name: video-moderation-service

  datasource:
    url: jdbc:postgresql://100.31.100.23:5432/streamnest
    username: streamnest_user
    password: StrongPassword@123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

aws:
    region: us-east-1
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    bucket-name: streaming-video-bucket-00

app:
  upload-path: ./uploads/videos
  frame-path: ./uploads/frames
  ffmpeg-path: ./ffmpeg/bin/ffmpeg.exe